# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 8",
  "iPhone 13"
])

languages([
  "en-US",
  "de-DE"
])

scheme("CatsAndModules_YanaBuha")
output_directory("./screenshots")
clear_previous_screenshots(true)
override_status_bar(true)